spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productgrowing
    username: system_takatan
    password: develop_admin_takatan
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl