version: '3'
services:
    mysql:
      build: ./mysql/
      volumes:
        - ./mysql/db:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=takatan
      ports:
        - '3306:3306'
