
/**
ProductGrowing
**/

/* create to Mysql connecton User And Database*/

CREATE USER 'system_takatan'@'%' IDENTIFIED BY 'develop_admin_takatan' ;

CREATE DATABASE `account`;

GRANT ALL PRIVILEGES ON `account`.* TO "system_takatan"@"%";

FLUSH PRIVILEGES;

USE account




CREATE TABLE ACCOUNT(
    ACCOUNTID int(11) unsigned AUTO_INCREMENT NOT NULL,
    ACCOUNTNAME VARCHAR(255),
    ACCOUNTPHONENUMBER VARCHAR(255), 
    CREATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ACCOUNTID)
);


INSERT INTO ACCOUNT (ACCOUNTNAME,ACCOUNTPHONENUMBER) VALUES("田中　太郎","090-1234-2222");
INSERT INTO ACCOUNT (ACCOUNTNAME,ACCOUNTPHONENUMBER) VALUES("中村　結衣","080-1542-3154");
INSERT INTO ACCOUNT (ACCOUNTNAME,ACCOUNTPHONENUMBER) VALUES("佐藤　ひなた","070-6284-4532");
INSERT INTO ACCOUNT (ACCOUNTNAME,ACCOUNTPHONENUMBER) VALUES("松本　秀夫","070-6284-4532");
